fc_image_loader:
  ds_dir: 'ds' # or file_name: (.txt or .csv with first row of 'names, labels')
  image_format:
    - 'jpeg'
    - 'png'
  image_resize: # or None
    width: 28
    height: 28
  image_crop: # or None
    x_coordinate: 0
    y_coordinate: 0
    width: 28
    height: 28
  labels: 'dir' # or filename (.txt, .csv) including filename, label


